name: "OctoPrint"
version: "0.0.2"
slug: "octoprint_addon"
description: "OctoPrint addon based on Octoprint docker"
arch:
  - armv7
  - amd64
  - armhf
  - aarch64
webui: http://[HOST]:[PORT:5000]
ports:
  80/tcp: 5000
ports_description:
  80/tcp: Web-based interface
devices:
# - "/dev/i2c-0"
# - "/dev/i2c-1"
# - "/dev/mem"
# - "/dev/gpiomem"
# privileged:
#   - SYS_RAWIO
# apparmor: false
# gpio: true
usb: true
uart: true
map:
  - config:rw
  - addons:rw
  - media:rw
  - share:rw
  - ssl
# options:
  # trusted_proxies: ""
  #camera_url: "http://b7aa59c4-camera-mjpg-streamer"
  # mode: normal
# schema:
  # trusted_proxies: "str?"
  # camera_url: "url?"
  # mode: "list(normal|recovery|reverse_proxy_test|camera)?"
# image: ghcr.io/fredrikbaberg/ha-addon-3dprinter-octoprint-{arch}
# codenotary:
tmpfs: true
# ingress: false
# ingress_stream: false
panel_icon: mdi:printer-3d
panel_title: OctoPrint HA
# stage: stable
init: false
realtime: true